name = "ws-server"
type = "javascript"

workers_dev = true
compatibility_date = "2024-06-01"

[durable_objects]
bindings = [{ name = "ROOM", class_name = "Room" }]

[[migrations]]
tag = "v1"
new_classes = ["Room"]
